Update latest version to 6.1.1
rails/homepage pull request #152
Opened 2021-01-08 02:39 UTC by koic

This PR updates the latest Rails version announcement link to 6.1.1.
https://weblog.rubyonrails.org/2021/1/7/Rails-6-1-1-has-been-released/

2021-01-09 20:37 UTC, bogdanvlviv commented on index.html
> +      <p class="show-mobile"><small>Released January 7, 2020</small></p>
2021 :)

2021-01-12 11:03 UTC, xuanxu approved these changes

2021-02-12 10:24 UTC, xuanxu requested changes
This is outdated now as 6.1.2.1 has been released:
https://weblog.rubyonrails.org/2021/2/10/Rails-5-2-4-5-6-0-3-5-and-6-1-2-1-have-been-released/

2021-02-12 10:24 UTC, xuanxu commented on index.html
> +      <p><a href="https://weblog.rubyonrails.org/2021/1/7/Rails-6-1-1-has-been-released/">Latest version &mdash; Rails 6.1.1 <span class="hide-mobile">released January 7, 2021</span></a></p>
```suggestion
      <p><a href="https://weblog.rubyonrails.org/2021/2/10/Rails-5-2-4-5-6-0-3-5-and-6-1-2-1-have-been-released/">Latest version &mdash; Rails 6.1.2.1 <span class="hide-mobile">released February 10, 2021</span></a></p>
```

2021-02-12 10:24 UTC, xuanxu commented on index.html
> +      <p class="show-mobile"><small>Released January 7, 2021</small></p>
```suggestion
      <p class="show-mobile"><small>Released February 10, 2021</small></p>
```

2021-02-12 18:19 UTC, koic commented
I've updated the latest Rails version mentioned in this PR to Rails 6.1.21.

2021-02-12 19:09 UTC, merged

2021-02-12 19:09 UTC, kaspth commented
Thank you!